config/routes.rb
Review::Application.routes.draw do

  resources :users, :sessions, :movies, :home , :comments

  root :to => 'home#index'
  match '/session/delete' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
     end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment}
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
         @comment.user_username = current_user.username
        format.html { redirect_to @comment, notice: 'comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= form_for(@comment) do |f|


  .field
    = f.collection_select :movie_title, Movie.all, :id, :title


  .field

    = f.label :review
    %br
    = f.text_area :review
    %br
  .field
    = f.label :rating
    %br
  .field
    =f.select :rating, [1,2,3,4,5,6,7,8,9,10]
    out of 10



    %br
  .actions
    = f.submit "Post"

app/views/comments/index.html.haml

= @comments.each do |comment|
  %td
    = comment.movie_title
  %td
    = comment.rating
  %td
    =comment.review

    =link_to "review" ,new_comment_path
    =link_to "check reviews"
  %br



%br

= link_to 'new comment', new_comment_path

app/views/comments/new.html.haml

= render 'form'


app/views/comments/show.html.haml
=notice
