config/routes.rb
Review::Application.routes.draw do

  resources :users, :sessions, :movies, :home , :comments

  root :to => 'home#index'
  match '/session/delete' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :movies
  has_many :comments

  before_save :create_remember_token



  validates :name,
            :presence => true ,
            :length => { :minimum => 2}

  validates :surname,
            :presence => true ,
            :length => { :minimum => 2}


  validates :password,
            :presence => true,
            :confirmation => true,
            :length => {:minimum => 6}


  validates :password_confirmation, :presence => true

  validates :email,
            :presence => true,
            :uniqueness => true


  validates_format_of  :email,
                       :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  ,
                       :message => " address invalid"
  validates :username,
            :presence => true,
            :length => {:minimum =>4},
            :uniqueness => true



     def has_password?(reg,the_pass)
         true if reg.password == the_pass

     end


    def self.authenticate(email , password)
        reg =  find_by_email(email)
      return nil if reg.nil?
      return reg if reg.has_password?(reg,password)


    end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json



  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show

    end


  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="field">
     <%= f.label :username %><br />
     <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>     <br />

    Confirm password <br />
    <%= f.password_field :password_confirmation %>    <br />
  </div>
  </div>
    <div>
      kind of movies?<br/>

      </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %>
<%= link_to 'Back', home_path%>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Surname</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.surname %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
 shizafo

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>